preferred_provider: azure_openai

providers:
  openai:
    api_key_env: OPENAI_API_KEY
    models:
      high: gpt-4
      low: gpt-3.5-turbo

  anthropic:
    api_key_env: ANTHROPIC_API_KEY
    models:
      high: claude-2
      low: claude-2

  gemini:
    api_key_env: GCP_PROJECT
    models:
      high: chat-bison@001
      low: chat-bison-lite@001

  azure_openai:
    api_key_env: AZURE_OPENAI_KEY
    api_endpoint_env: AZURE_OPENAI_ENDPOINT
    models:
      high: gpt-4
      low: gpt-3.5-turbo