# https://taskfile.dev

version: '3'

vars:
  GREETING: Welcome to NL Web!

tasks:
  check:
    cmds:
      - python azure-connectivity.py 
    dir: ./code
  app:
    cmds:
      - python app-file.py
    dir: ./code
  deploy:openai:
    cmds:
      - ./setup.sh -d
    dir: ./scripts
  cleanup:
    cmds:
      - ./remove.sh -d
    dir: ./scripts
  run:
    cmds:
       - task: deploy:openai
       - task: check
       - task: app
    dir: ./infra
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
