preferred_endpoint: azure_ai_search_1

endpoints:
  azure_ai_search_1:
    api_key_env: AZURE_VECTOR_SEARCH_API_KEY
    api_endpoint_env: AZURE_VECTOR_SEARCH_ENDPOINT
    index_name: embeddings1536
    db_type: azure_ai_search
    name: NLWeb_Crawl

  azure_ai_search_2:
    api_key_env: AZURE_VECTOR_SEARCH_API_KEY
    api_endpoint_env: AZURE_VECTOR_SEARCH_ENDPOINT
    index_name: embeddings1536
    db_type: azure_ai_search
    name: Bing_Crawl
      

  milvus_1:
    database_path: ../milvus/milvus_prod.db
    index_name: prod_collection
    db_type: milvus