preferred_endpoint: azure_ai_search_1

endpoints:
  azure_ai_search_1:
    api_key_env: AZURE_VECTOR_SEARCH_API_KEY
    api_endpoint_env: AZURE_VECTOR_SEARCH_ENDPOINT
    index_name: embeddings1536
    db_type: azure_ai_search
    name: NLWeb_Crawl

  azure_ai_search_2:
    api_key_env: AZURE_VECTOR_SEARCH_API_KEY
    api_endpoint_env: AZURE_VECTOR_SEARCH_ENDPOINT
    index_name: embeddings1536
    db_type: azure_ai_search
    name: Bing_Crawl
      

  milvus_1:
    database_path: ../milvus/milvus_prod.db
    index_name: prod_collection
    db_type: milvus

  qdrant:
    # To connect to a Qdrant server, set the `QDRANT_URL` and optionally `QDRANT_API_KEY`.
    # > docker run -p 6333:6333 qdrant/qdrant
    # QDRANT_URL="http://localhost:6333"
    api_endpoint_env: QDRANT_URL
    api_key_env: QDRANT_API_KEY

    # To use a local persistent instance for prototyping,
    # set database_path to a local directory
    database_path: "/path/to/some/directory"

    # Set the name of the collection to use as `index_name`
    index_name: nlweb_collection
    db_type: qdrant